site_name: Opensafely EHR Dataset Metadata Directory
theme:
  name: material
  features:
    - content.code.annotate
plugins:
  - include-markdown
  - tags:
      tags_file: tags.md
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences