site_name: Opensafely Phenotype Wiki
theme:
  name: material
  features:
    - content.code.annotate
plugins:
  - tags:
      tags_file: tags.md
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences